# ResNet50-based 7x7x3 anchor boxes detector
model:
  name: best_detector

# Train algorithm
trainer:
  name: train_fine_tune

# Custom loss config
loss:
  name: best_detector
  params:
    class_weight:
      - 1.
      - 0.5

# Optimizer config
optimizer:
  name: adam
  params:
    lr: 0.003
    amsgrad: True

# Learning rate sheduler config
lr_sheduler:
  name: step_lr
  params:
    step_size: 20
    gamma: 0.1

# Early stop detector config
early_stop:
  name: default
  params:
    max_steps: 5
    reverse: False

# Max train epochs
epochs: 100

# Path to save model
save_path: model
